if(UNIX)
   add_compile_options(-finput-charset=UTF-8)
   add_compile_options(-fexec-charset=UTF-8)
elseif(WIN32)
   add_compile_options(/utf-8)
endif()
#让所有项目都使用UNICODE
add_definitions(-D_UNICODE -DUNICODE)

# ===========================================================打包函数===========================================================
function(ezui_add_resources TARGET_NAME INPUT_DIR OUTPUT_FILE)
    # 定义始终运行的伪目标
    add_custom_target(
        ${TARGET_NAME}_ResPackage  # 更简洁的目标命名
        COMMAND ${CMAKE_SOURCE_DIR}/ResPackage.exe -package ${INPUT_DIR} ${OUTPUT_FILE}
        COMMENT "Packaging resources for ${TARGET_NAME}..."
    )
    # 将目标归类到专用文件夹
    set_target_properties(${TARGET_NAME}_ResPackage PROPERTIES
        FOLDER "EzUIBuildUtilities"  # 在VS中归类到指定文件夹
    )
    # 主目标依赖伪目标
    add_dependencies(${TARGET_NAME} ${TARGET_NAME}_ResPackage)
endfunction()

#===========================================================初始化项目,在每个项目的CMakeLists.txt中调用此函数,传入项目名称和项目目录===========================================================
function(ezui_init_project projectName projectDir)
    set(RC_FILE  "${projectDir}/ezui_${projectName}.rc")
    set(RES_DIR  "${projectDir}/ezui_res")
    set(RES_FILE "${projectDir}/ezui_${projectName}.res")
    # 确保资源目录存在
    file(MAKE_DIRECTORY "${RES_DIR}")
    # 生成 rc 文件（仅第一次）
    if(NOT EXISTS "${RC_FILE}")
        message(STATUS "Creating EZUI resource file: ${RC_FILE}")
        file(WRITE "${RC_FILE}" 
            "// Auto generated by EZUI\n"
            "#include <windows.h>\n"
            "my_res EZUI_RES \"ezui_${projectName}.res\"\n"
        )
    endif()
    # 如果 target 已存在才添加资源
    target_sources(${projectName} PRIVATE "${RC_FILE}")
        file(GLOB_RECURSE res_files CONFIGURE_DEPENDS "${RES_DIR}/*.*")
        if(res_files)
            target_sources(${projectName} PRIVATE ${res_files})
            source_group(TREE "${RES_DIR}" PREFIX "ezui_res" FILES ${res_files})
     endif()
    # 添加资源打包
    ezui_add_resources(${projectName} "${RES_DIR}" "${RES_FILE}")
endfunction()

# ===========================================================链接EzUI库,在每个项目的CMakeLists.txt中调用此函数,传入项目名称===========================================================
function(ezui_add_lib projectName)
    set(ezui_include_dir "D:/C++/EzUI/include")#根据实际情况修改为你的EzUI库的头文件目录
    set(ezui_build_dir "D:/C++/EzUI/build_x64")#根据实际情况修改为你的EzUI库的构建目录
    # 设置 Debug/Release 类型
    set(Build_Type "$<IF:$<CONFIG:Debug>,Debug,Release>")
    # 包含头文件路径
    target_include_directories(${projectName} PRIVATE ${ezui_include_dir})
    # 链接库文件
    target_link_libraries(${projectName} PRIVATE
        "${ezui_build_dir}/${Build_Type}/EzUI.lib"
    )
endfunction()

#include(CommonConfig.cmake)//在所需Cmakelist.txt文件导入此通用配置
#AddConfig(Your_Target)//为项目添加通用配置
#target_compile_definitions(test PRIVATE WIN32_LEAN_AND_MEAN) #添加一个宏,避免socket冲突
#set_target_properties(DiskCleaner PROPERTIES  LINK_FLAGS "/MANIFESTUAC:\"level='requireAdministrator' uiAccess='false'\"" ) #设置管理员启动权限