#pragma once
#include <iostream>
#include <string>
#include <functional>
#include <fstream>
#include <vector>
#include <sstream>
#include <mutex>
#include <memory>
#include <map>
#include <io.h>
#include <Windows.h>
#include <winuser.h>
#include <assert.h>

#include "Text.h"
#include "FileSystem.h"
#include "DateTime.h"
#include "WinTool.h"
#include "WebClient.h"
#include "JsonCpp.hpp"
#include "Log.h"
#include "ThreadPool.hpp"
#include "IniConfig.h"
